export enum Column {
  FIRST_NAME = 'Имя',
  LAST_NAME = 'Фамилия',
  PATRONYMIC = 'Отчество',
  CAR = 'Автомобиль',
  PRICE = 'Цена',
  DESTINATION = 'Откуда',
  REQUEST = 'Договор заявка',
  DOC_NUMBER = 'Номер акта',
  INFO = 'Информация',
  NAME = 'Название',
  CLIENT = 'Компания',
  IS_READY = 'Готовность актов',
  FULL_NAME = 'ФИО',
  MANAGER = 'Менеджер',
  DATE = 'Дата и время загрузки',
}
